name: stream_loader_demo
description: stream_loader demo
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  distinct_value_connectable_stream: ^1.0.3+1
  responsive_builder: ^0.1.4
  http: ^0.12.0+4
  built_value: ^7.0.8
  stream_loader: ^0.1.0
  disposebag: ^1.1.1+1
  rx_shared_preferences: ^1.1.1+1
  random_string: ^2.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  built_value_generator: ^7.0.8
  build_runner: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/new_year_2021.jpg
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf