name: stream_loader_demo
description: stream_loader demo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  distinct_value_connectable_stream: ^1.2.0-nullsafety.2
  responsive_builder: ^0.3.0
  http: ^0.12.2
  built_value: ^7.1.0
  stream_loader: ^1.1.0-nullsafety.0
  disposebag: ^1.5.0-nullsafety.0
  rx_shared_preferences: ^1.3.5
  random_string: ^2.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  built_value_generator: ^7.1.0
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  rxdart: ^0.26.0-nullsafety.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/new_year_2021.jpg
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf